stages:
  - build
  - test

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker build -t my-python-app .

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=report.xml
  artifacts:
    paths:
      - report.xml
    expire_in: 1 week
