stages:
  - deploy

deploy:
  stage: deploy
  script:
    - chmod +x deploycheck.sh 
    - ./deploycheck.sh $ENV
  parallel:
    matrix:
      - ENV: dev
      - ENV: staging
      - ENV: prod
include:
  - project: 'template_proj/ci-templates'
    file: '/.common-variables.yml'
    ref: main